name = "SQL-Concat"
# badges = ["travis"]
authority="cpan:HKOBA"

module_maker="ModuleBuildTiny"

abstract_from = "lib/SQL/Concat.pod"
authors_from  = "lib/SQL/Concat.pod"
readme_from   = "lib/SQL/Concat.pod"
markdown_maker = "Pod::Markdown::Github"

license = "perl_5"
badges = ['travis']

[Metadata]
x_static_install = 1
